// utils/translateToUrdu.ts

const translations: Record<string, string> = {
   'the': 'یہ',
  'and': 'اور',
  'is': 'ہے',
  'are': 'ہیں',
  'to': 'کو',
  'of': 'کا',
  'in': 'میں',
  'for': 'کے لیے',
  'with': 'کے ساتھ',
  'on': 'پر',
  'at': 'پر',
  'by': 'کے ذریعے',
  'this': 'یہ',
  'that': 'وہ',
  'will': 'گا',
  'can': 'کر سکتے ہیں',
  'technology': 'ٹیکنالوجی',
  'development': 'ترقی',
  'software': 'سافٹ ویئر',
  'application': 'ایپلیکیشن',
  'system': 'نظام',
  'data': 'ڈیٹا',
  'user': 'صارف',
  'users': 'صارفین',
  'website': 'ویب سائٹ',
  'blog': 'بلاگ',
  'article': 'مضمون',
  'content': 'مواد',
  'information': 'معلومات',
  'business': 'کاروبار',
  'company': 'کمپنی',
  'market': 'بازار',
  'product': 'پروڈکٹ',
  'service': 'خدمات',
  'digital': 'ڈیجیٹل',
  'online': 'آن لائن',
  'internet': 'انٹرنیٹ',
  'mobile': 'موبائل',
  'app': 'ایپ',
  'platform': 'پلیٹ فارم',
  'innovation': 'جدت',
  'future': 'مستقبل',
  'world': 'دنیا',
  'new': 'نیا',
  'modern': 'جدید',
  'important': 'اہم',
  'popular': 'مقبول',
  'effective': 'مؤثر',
  'successful': 'کامیاب',
  'help': 'مدد',
  'support': 'سپورٹ',
  'solution': 'حل',
  'problem': 'مسئلہ',
  'way': 'طریقہ',
  'time': 'وقت',
  'work': 'کام',
  'working': 'کام کرنا',
  'people': 'لوگ',
  'team': 'ٹیم',
  'project': 'پروجیکٹ',
  'experience': 'تجربہ',
  'design': 'ڈیزائن',
  'create': 'بنانا',
  'build': 'تعمیر کرنا',
  'develop': 'تیار کرنا',
  'improve': 'بہتر بنانا',
  'process': 'عمل',
  'result': 'نتیجہ',
  'benefits': 'فوائد',
  'features': 'خصوصیات',
  'tools': 'اوزار',
  'resources': 'وسائل',
  'management': 'انتظام',
  'strategy': 'حکمت عملی',
  'growth': 'اضافہ',
  'success': 'کامیابی',
  'quality': 'معیار',
  'performance': 'کارکردگی',
  'security': 'سیکیورٹی',
  'privacy': 'پرائیویسی',
  'simple': 'آسان',
  'easy': 'آسان',
  'fast': 'تیز',
  'efficient': 'مؤثر',
  'best': 'بہترین',
  'better': 'بہتر',
  'good': 'اچھا',
  'great': 'بہترین',
  'excellent': 'بہترین',
  'amazing': 'حیرت انگیز'
};

export const translateToUrdu = (text: string): string => {
  let translatedText = text;

  Object.keys(translations).forEach(englishWord => {
    const regex = new RegExp(`\\b${englishWord}\\b`, 'gi');
    translatedText = translatedText.replace(regex, translations[englishWord]);
  });

  return translatedText;
};
